name: demo-streamlit-heroku
channels:
- conda-forge
dependencies:
- python=3.8
- conda
- pandas
- numpy
- matplotlib
- seaborn
- scipy
- scikit-learn
- pip
- os
- matplotlib.pyplot 
- pickle
- pip:
  - streamlit


